# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 277da58f4df02375e2d4a55204248b7e3cdbb0470286db8a95799f21b6a48fa36d7052a19d2bde282ecc68f93d56a1b4341958b6483977b8af5e6fa66c8c954a

test:
  secret_key_base: e36969d28c7ca790170f97afb672476e3b514c31e8e445d06695af76ffe601086fc5fdae8542ace694a01b5985ac1a365f5a351a18a87e2d4ac27c263c7140c8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
